# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f67006ca46f4b12d5ad38ce7c2c0295554f1c0b5e89bcbea6e5cf5f94cf4ed41012f72aa2b9217b9823a8dccefdad3427780059d87332ee0a7d33b0bb4e3d4f

test:
  secret_key_base: f0248996b43d87d673f3a40115edf9c75548240d4665a5615effc8faff03f36d98e2296b146647efc5639fdb0046b9916e3a1a4c7e68f7f2da0d731675d2e5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
