# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea9f76a50e10697fd32ddbabfdab187fc269a7c93921036fc33cb9b9a2d17cbe4cd3ae7f3eb0349778ac0ba9ad3658ca2c5e539d5963c04347bfcb33281e96e3

test:
  secret_key_base: a3c9009ac27a7042e1ac6e1a9719c6acd3a51d3dfad4b05300c3fbe110b0c5313fbbaaf6ec3c04f9eb37a63ea61016b83273a0781dac5094fc7cdce0dc3540ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
